#!/usr/bin/python
#---------------------------------------------------------------
# Project         : pxemngr
# File            : addsystem
# Version         : $Id$
# Author          : Frederic Lepied
# Created On      : Sun Feb  1 13:54:41 2009
# Purpose         : 
#---------------------------------------------------------------

import sys
import settings
from pxe.models import *
from pxe.common import *

if len(sys.argv) < 3:
    error('Usage: %s <system name> <MAC> [<MAC2>...]' % sys.argv[0])

try:
    system = System.objects.get(name=sys.argv[1])
except System.DoesNotExist:
    system = System(name=sys.argv[1])
    system.save()

for addr in sys.argv[2:]:
    a = simplify_mac(addr)
    try:
        mac = MacAddress.objects.get(mac=a)
        if mac.system != system:
            mac.system = system
            mac.save()
    except MacAddress.DoesNotExist:
        mac = MacAddress(mac=a, system=system)
        mac.save()

# addsystem ends here
