#!/usr/bin/python
#---------------------------------------------------------------
# Project         : pxemngr
# File            : addsystem
# Copyright       : 2009 Splitted-Desktop Systems
# Author          : Frederic Lepied
# Created On      : Sun Feb  1 13:54:41 2009
# Purpose         : add a system and its mac addresses to the
#                  database.
#---------------------------------------------------------------

import sys
import settings
from pxe.models import *
from pxe.common import *

if len(sys.argv) < 3:
    error('Usage: %s <system name> <MAC> [<MAC2>...]' % sys.argv[0])

if sys.argv[1] == 'default':
    error('default is a reserved name and cannot be used for a system name')
    
try:
    system = System.objects.get(name=sys.argv[1])
except System.DoesNotExist:
    system = System(name=sys.argv[1])
    system.save()

for addr in sys.argv[2:]:
    if addr.index('.') >= 0:
        a = simplify_ip(addr)
    else:
        a = simplify_mac(addr)
    try:
        mac = MacAddress.objects.get(mac=a)
        if mac.system != system:
            mac.system = system
            mac.save()
    except MacAddress.DoesNotExist:
        mac = MacAddress(mac=a, system=system)
        mac.save()

# addsystem ends here
