#!/usr/bin/python
#---------------------------------------------------------------
# Project         : pxe
# File            : delsystem
# Copyright       : 2010 Splitted-Desktop Systems
# Author          : Frederic Lepied
# Created On      : Wed May 12 10:01:29 2010
# Purpose         : delete the database entries for a given system
#---------------------------------------------------------------

import sys
from pxe.models import *
import settings
from pxe.common import *

if len(sys.argv) != 2:
    error('Usage: %s <system name>' % sys.argv[0])

try:
    system = System.objects.get(name=sys.argv[1])
except System.DoesNotExist:
    error('System %s not defined' % sys.argv[1])

list = ['%s/%s' % (settings.PXE_ROOT, system.name), ]

for m in MacAddress.objects.filter(system=system):
    list.append(mac2path(m.mac))

for f in list:
    try:
        os.unlink(f)
    except OSError:
        pass

system.delete()

# delsystem ends here
