#!/usr/bin/python
#---------------------------------------------------------------
# Project         : pxemngr
# File            : dpysystem
# Version         : $Id$
# Author          : Frederic Lepied
# Created On      : Sun Feb  1 13:54:41 2009
# Purpose         : 
#---------------------------------------------------------------

import sys
import settings
from pxe.models import *
from pxe.common import *

if len(sys.argv) != 2:
    error('Usage: %s <system name>' % sys.argv[0])
    
try:
    system = System.objects.get(name=sys.argv[1])
except System.DoesNotExist:
    error('System %s not defined' % sys.argv[1])

print 'Name:', system.name

for mac in MacAddress.objects.filter(system=system):
    print 'Mac:',
    for i in range(0, 10, 2):
        sys.stdout.write('%s:' % mac.mac[i:i+2])
    sys.stdout.write('%s\n' % mac.mac[10:12])

logs = Log.objects.filter(system=system).order_by('-date')
if len(logs) >= 1:
    print 'Next boot:', logs[0].boot_name.name

print 'History:'
for l in logs[1:]:
    print l.date, l.boot_name.name
    
# addsystem ends here
