#!/usr/bin/python
#---------------------------------------------------------------
# Project         : pxemngr
# File            : nextboot
# Copyright       : 2009 Splitted-Desktop Systems
# Author          : Frederic Lepied
# Created On      : Sun Feb  1 13:54:41 2009
# Purpose         : configure the profile for the next PXE boot
#                   of a system.
#---------------------------------------------------------------

import sys
import os
import settings
from pxe.models import *
from pxe.common import *

if len(sys.argv) != 3:
    error('Usage: %s <system name> <boot name>' % sys.argv[0])

name = sys.argv[1]

try:
    system = System.objects.get(name=name)
except System.DoesNotExist:
    if name == 'default':
        system = System(name=name)
        system.save()
    else:
        error('System %s not defined' % name)

set_next_boot(system, sys.argv[2])

# nextboot ends here
